import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { VariableContextProvider } from '@tr/frontend/contexts/variable.context';
import { AuthProvider } from '@tr/frontend/contexts/auth.context';
// import { asdf } from '~/src/app/page';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <VariableContextProvider
          variables={{
            BACKEND_URL: process.env.BACKEND_URL,
          }}
        >
          <AuthProvider>{children}</AuthProvider>
        </VariableContextProvider>
      </body>
    </html>
  );
}
